jobs:
    - name: kube-fun_runCI
      type: runCI
      steps:
          - OUT: app-image

    - name: app-manifest
      type: manifest
      steps:
          - IN: app-image

    - name: app-deploy
      type: deploy
      steps:
          - IN: app-manifest
          - IN: app-cluster